# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 048963765f1e2227fd3dff4a3a43af283f7ebaa7b53f9c381be3c7f256d458a9135bd201a7a8e6fde49c388e29f884ce9f6741eb7a45014a494182af7528dcd2

test:
  secret_key_base: 3f2569982644c26c7944a9dae948223b16209a960eb429e274dbde5ac42cdbdc2650df0b6cd88ed3d4629dc8af8f2935d3dee0cd52f53fca50443d374f50221b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
